### ISSUE TITLE
刚好可以拿过来用……牛

### ISSUE THREAD

**Issue by yangchong211** [youlookwhat/WebProgress#1]

**Comment by youlookwhat** [comment]
拿来用可以，希望你标明来源，尊重一下作者！

**Comment by yangchong211** [comment]
感谢大神，已经在github上备注了信息，参考了你的项目，多谢

**Comment by youlookwhat** [comment]
对于这个类，我可没看到，这个类的署名都是你的。

https://github.com/yangchong211/YCWebView/blob/master/WebViewLib/src/main/java/com/ycbjie/webviewlib/WebProgress.java

**Comment by youlookwhat** [comment]
/**
 * WebView进度条，原作者: cenxiaozhong，在此基础上修改优化：
 * 1. progress同时返回两次100时进度条出现两次
 * 2. 当一条进度没跑完，又点击其他链接开始第二次进度时，第二次进度不出现
 * 3. 修改消失动画时长，使其消失时看到可以进度跑完
 * 4. [2019.9.29] 修复当第一次进度返回 0 或超过 10，出现不显示进度条的问题
 * 5. 能显示渐变色
 *
 * @author jingbin
 * Link to https://github.com/youlookwhat/WebProgress
 */

这是我在上面写的，你有一点尊重吗

**Comment by yangchong211** [comment]
好的，我只是在readme中写了

**Comment by yangchong211** [comment]
我加上

**Comment by yangchong211** [comment]
大神，对不起，我已经加上了，我之前都是在readme中写的，后期我会注意的
